services:
  - type: web
    name: coachsam-backend
    runtime: node
    repo: https://github.com/moha84100/coachsam-website
    rootDir: ./backend
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: MONGO_URI
        sync: false # This will be manually set by the user from MongoDB Atlas
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: JWT_SECRET
        generateValue: true
